"""Ratings table

Revision ID: 7c3bd17a7133
Revises: 
Create Date: 2024-01-07 18:48:43.957360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3bd17a7133'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album', sa.String(length=256), nullable=False),
    sa.Column('artist', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_album'), ['album'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_artist'), ['artist'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_artist'))
        batch_op.drop_index(batch_op.f('ix_rating_album'))

    op.drop_table('rating')
    # ### end Alembic commands ###
